// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
//  import 'firebase_options.dart';
// /// // ...
//  await Firebase.initializeApp(
//    options: DefaultFirebaseOptions.currentPlatform,
//  );
///
///
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhn44zvWV3G01Xusy2fye97LL0FdkUAdI',
    appId: '1:865130205176:web:b0fa509e1f37c14873900d',
    messagingSenderId: '865130205176',
    projectId: 'placeverse-1510c',
    authDomain: 'placeverse-1510c.firebaseapp.com',
    storageBucket: 'placeverse-1510c.appspot.com',
    measurementId: 'G-Q67FZ0LS3W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEoHGyiqrxLBlN2QHP-4UrOk8DVe6w6dE',
    appId: '1:865130205176:android:5c92414d31de7a5b73900d',
    messagingSenderId: '865130205176',
    projectId: 'placeverse-1510c',
    storageBucket: 'placeverse-1510c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPJheHRVVYi0aKx_aB67bVIenL1_xRAJQ',
    appId: '1:865130205176:ios:3597e825ea53249a73900d',
    messagingSenderId: '865130205176',
    projectId: 'placeverse-1510c',
    storageBucket: 'placeverse-1510c.appspot.com',
    iosClientId: '865130205176-d86dgihsd5db54kf7pb3ea9qabb7feu9.apps.googleusercontent.com',
    iosBundleId: 'com.yash.placeverse.placeverse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPJheHRVVYi0aKx_aB67bVIenL1_xRAJQ',
    appId: '1:865130205176:ios:3597e825ea53249a73900d',
    messagingSenderId: '865130205176',
    projectId: 'placeverse-1510c',
    storageBucket: 'placeverse-1510c.appspot.com',
    iosClientId: '865130205176-d86dgihsd5db54kf7pb3ea9qabb7feu9.apps.googleusercontent.com',
    iosBundleId: 'com.yash.placeverse.placeverse',
  );
}
